locale: "ko-KR"
title: Jeongwonniii Blog
author: Jeongwon Min
email: jmin8694@snu.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Jeongwon Min
  tagline: ‚úèÔ∏è‚ù£Ô∏èüìö
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  #dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/profile_photo.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: samarsault
    github:  MinJeongwon
    #linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: jmin8694@snu.ac.kr

  navigation:
    - title: About
      url: "/about"
    - title: Work
      url: "/work"

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: plainwhite
#remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false #https://junsk1016.github.io/markdown/%EC%88%98%EC%8B%9D-%EC%A0%81%EC%9A%A9%EC%8B%9C%EC%BC%9C%EC%84%9C-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0/